### ISSUE TITLE
Metadata z NDK balicku

### ISSUE THREAD

**Issue by bodnarIQ** [LIBCAS/DL4DH#12]
Potrebovali by sme nadefinovať, ake konkrétne metadáta sa majú preberať z NDK balíčkov, a podľa čoho sa má dať filtrovať a vyhľadávať, aby sme podľa toho mohli nadefinovať fieldy pre indexovanie a mohli začať spresňovať model objektu, v ktorom sa budú ukladať metadáta vzťahujúce sa k stránke, prípadne k celej publikácií. 

Príklad NDK balíčku máme (pre publikáciu [Bohemia](https://kramerius.lib.cas.cz/view/uuid:ba1b36ab-17bf-4eb1-801a-27172cd62faa?page=uuid:0c00e1f2-8578-4b88-a6a5-64a78bd35cc0)).

**Comment by inqool-bukovsky** [comment]
prozkoumat možnosti získávání dat z LTP. 
@zabak a Michal Indrák

**Comment by bukovskyIQ** [comment]
Zdravíme, potřebovali bychom vaši součinnost při tomto issue.
@MLhotak @zabak

**Comment by zabak** [comment]
Jak se ukázalo, některé informace (kvalita OCR) bude nutné dodat z workflow digitalizačního systému, nejsou součástí balíčku. Obecně by bylo nejlepší mít prostřednictvím K+ k dispozici úplná metadata z daných balíčků s tím, že některé základní údaje (např. DPI, použitý scanner apod.) by mohly být i indexované. @bodnarIQ Mohl bych ten balíček Bohemie dostat taky, ať se všichni bavíme nad stejnými vzorky?

**Comment by bukovskyIQ** [comment]
Aktuálně jsme Vám @zabak přeposlali email od p. Lhotáka s požadovanou přílohou (balíček). 

Můžete prosím konkretizovat jaká metadata máme přebírat z NDK balíčků ? Děkuji.

**Comment by JanMeritus** [comment]
@bukovskyIQ prosim taky o preposlani

**Comment by bodnarIQ** [comment]
keďže link z mailu nefungoval, nahral som NDK balíček na google drive, prikladám odkaz (prístupný iba ľudom ktorý majú prístup do adresára `DL4DH - spolupráca s KNAV`)

https://drive.google.com/file/d/1hpk2bnigWM3-PBM3QjHQIPjyOBvKTj4X/view?usp=sharing

**Comment by bukovskyIQ** [comment]
Dobrý den, @zabak @MLhotak,

prosíme o update k NDK balíčkům, jaká konkrétní metadata se budou přebírat.

**Comment by bukovskyIQ** [comment]
Dobrý den, 

aktuálně se blížíme do stavu, kdy bychom potřebovali mít jasno v tom, jaká metadata se mají přebírat z NDK balíčků.

Měla k tomu sloužit tato tabulka, která se nám jeví jako draft verze. Potřebovali bychom ji brzy finalizovat a začít tak s implementací přebírání metadat dle Vašich potřeb.

- https://docs.google.com/spreadsheets/d/1u4s54vPdVQ6eg58vbt3kLenQylSVK9Zn1YKILIExTyI/edit#gid=0

Pro ujasnění, v tabulce, kde je znak **x** se myslí, že se s těmito metadaty bude pracovat, je tato úvaha správná ?

Prosím o doplnění, jež mělo být dle společné dohody finální k 28.7.

V případě potřeb nás kontaktujte :)

**Comment by MLhotak** [comment]
Dobrý den,

x mělo/má znamenat, že s tím počítáme pro převzetí, případně i pro indexaci. Už během minulé schůzky se však bohužel ukázalo, že na ní nebudeme schopni vše rozhodnout. Slíbil jsem, že to projednám s kolegyní, která tabulku připravila. To jsem udělal a ona nyní připravuje její aktualizaci - něco se rozpadne do více podpolí a k většině by měly být uvedeny příklady. Pak to budeme muset znovu projednat na schůzce. Bude to tedy opět podklad jednání, kde bude více detailů. Počítám, že se na to znovu podíváme 27. 8. V tuto chvíli tedy nemá smysl, aby inQool tabulku využil.
