### ISSUE TITLE
Proces plnenia pomocnej databázy K+

### ISSUE THREAD

**Issue by bodnarIQ** [LIBCAS/DL4DH#2]
Akým spôsobom bude prebiehať plnenie databázy K+ ?

V K+ vystavíme API, cez ktoré budú administrátori systému schopný vybrať publikáciu/sadu publikácií do K+. V tomto kroku dôjde nahratiu základných dát z K do K+ (hlavne textový obsah OCR). Obohatenie publikácií metadátami z externých služieb(UdPipe, NameTag, ...) bude prebiehať buď už pri napĺňaní(API može príjmať parametre pre určenie, akými službami chceme dáta obohatiť už pri prvotnom napĺňaní) a taktiež bude vystavené samostatné API pre obohatenie/znovu obohatenie v neskorších fázach pre publikácie už obsiahnuté v K+. 

Akým spôsobom ale administrátor systému vyberie, ktoré publikácie chce takto dostať do K+?
1. Pošle v API dotaze parameter `ID` publikácie, a K+ si cez API Krameriusu stiahne vybranú publikáciu.
2. Pošle v API dotaze parameter `zoznam ID` publikácií, K+ si cez API Krameriusu stiahne sadu publikácií.
- pre obe tieto možnosti budeme potrebovať vystaviť API v Krameriuse pre stiahnutie publikácie
3. Pošle v API dotaze celý objekt publikácie - neefektívne, vysoká chybovosť
4. Bude vystavené v K+ aj API pre automatické hromadné sťahovanie (niečo ako "stiahnutie celého obsahu z K" s možnosťami nejakých filtrov, ako napríklad "publikácie typy monografie s počtom stránok < 100" pre nejaké systematické, postupné napĺňanie v neskorších fázach). Pre fungovanie takéhoto API bude musieť K+ volať API K, ktoré na to bude musieť byť pripravené. 

Prvé dva body sú vhodné pre manuálne napĺňanie, pravdepodobne využité iba vo fázach testovania, prípadne pre dodatočné doplnenie nejakého obsahu, ale pri množstve publikácií v K potrebujeme aj nejaký automatický spôsob napĺňania.

Prosím o doplnenie prípadne opravu, ak sú niektoré body zle, alebo ak si plnenie DB K+ predstavujete inak.

**Comment by bodnarIQ** [comment]
Z [dokumentacie](https://github.com/ceskaexpedice/kramerius/wiki/RemoteAPI) Krameriusu vidim vystavene API pre ziskanie FOXML suboru na zaklade ID(bod č. 1 vyššie), wiki ale popisuje API krameriusu v4.6, bude API pre K7 zhodné?

**Comment by inqool-bukovsky** [comment]
@MLhotak

**Comment by bukovskyIQ** [comment]
Zdravíme, potřebovali bychom vaši součinnost při tomto issue.
@MLhotak @zabak @JanMeritus

**Comment by JanMeritus** [comment]
@bodnarIQ podobny ukol sme riesili v inej suvislosti a mame to osetreno nasledovne: C. 2, je na uvod idealne, bohuzel pro produkci je to znacne nevhodne. C4 nasledne. Je otazne kdo s tim bude moci operovat, pokud by to meli byt jenom admini staci fakt neco minimalistickeho.

V tom momente by bolo by vhodne aby tam bolo nejake minimalisticke spravcovske rozhranie, ktore natiahne obsah Kram (primarne root UUID a ich podrazene UUID (bez page), a pro krasu kontextu napr Nazev, Rocnik, Autory, Prava ), bola by moznost ich vyklikat / vyfiltroval / dat all, a poslat na spracovanie, stav spracovania by sa zde zobrazoval taky, vcetne chyb. Urcite bude nutne ale osetrit pravami, pripadne batchovanim objem spracovavaneho, protoze ukliknuti muze vyvolat neprijemne dusledky. Akce by taky mohla byt casovana / schedulovana.

**Comment by zabak** [comment]
@JanMeritus @MLhotak nebylo by lepší držet obsah K+ synchronní s K a neřešit manuální synchronizaci? Co se týče sbírek, měli bychom rozlišit oficiální sbírky (už ale ty nové ve stylu K7) a pak sbírky které si vyrobí uživatel lokálně v K+ pro účely svého výzkumu. Bude i tyto "privátní" sbírky vytvářet už v Krameriu?

**Comment by JanMeritus** [comment]
@zabak za mne je synchronizace optimalni automaticky. Nicmene realne spousteni obohacovani v K+  by melo byt moci regulovano i jinak, nebot je mozne ze dojde k zahlceni. Privatni sbirky (rsp skor jejich spracovani) bude urcite nutne povolovat z K+ a taky tam aj nejak regulovat, inak si umim predstavit jak to rychle zacne rust

**Comment by bodnarIQ** [comment]
> ... Urcite neresit primym preposilanim dat.

Súhlas, toto samozrejme nepripadá v úvahu.

Mohol by som poprosiť o podrobnejšie informácie(alebo odkaz k nim) k užívateľským zbierkam/kolekciam v K(kto ich moze vytvarat, kedy, ako, ake atributy obsahuje, co sa s nimi da v K robit, a pod.)? V požiadavkach je to spomenuté iba veľmi stručne, a na wiki K som o tom nič nenašiel.

**Comment by JanMeritus** [comment]
obsahovy spravci, metodika zatim neexistuje, tvorena v MZK @zabak , prosim o vyjadreni s predstavou Janku Hrzinovu (odkaz preposlan)

**Comment by JanaHrzinova** [comment]
Dobrý den, obecně a na uživatelské úrovni v NK sbírky vytváří kurátor Krameria. Prozatím byla startegie taková, že dával dohromady celky volně dostupných dokumentů. Sbírka se dá vytvořit, zrušit. Dílo do sbírky zařadit/vyřadit. Potom se ke sbírkám (jednotlivým celkům) dá přidat anotace a obrázkový náhled. Ve vlastnostech sbírky se dá nastavit český název a anglický název. Potom se dají nastavit snad i práva, kdo může sbírku číst, administrovat, provádět replikace, tisknout dokumenty a přistupovat k pdf. S těmito nastaveními nemám ale žádné zkušenosti a k technickému fungování toho nedokážu mnoho říct.

**Comment by zabak** [comment]
@JanMeritus Metodiku budeme dělat, ale počítali jsme s tím, že nejprve bude software (aspoň v prvním prototypu) a na to naváže metodika
