### ISSUE TITLE
Labels a testovani

### ISSUE THREAD

**Issue by JanMeritus** [LIBCAS/DL4DH#31]
muzu pozadat o prava k pridavani labels - pro zlepseni RFC a issues cyklu

**Comment by JanMeritus** [comment]
Duplicita s LIBCAS/DL4DH#28 , nevim jak vic zaurgovat @MLhotak

**Comment by JanMeritus** [comment]
@MLhotak zde se pripominam ad labels

**Comment by daliboris** [comment]
Taky se moc přimlouvám, u testování by se např. hodilo rozdělení na různé fáze (obohacení, export) a formáty (JSON, CSV, TEI).

**Comment by daliboris** [comment]
Ještě jedna připomínka k @MLhotak: nemohli bychom štítky přidělovat i my ostatní? Můžu vytvořit issue (viz např. LIBCAS/DL4DH-Kramerius-plus#46), ale nemůžu u něj nastavit labely. To nejspíš zatím může jenom @JanMeritus, což ho bude zbytečně zatěžovat.
