### ISSUE TITLE
Prosim o zapojeni testovaci instance vuci NK

### ISSUE THREAD

**Issue by JanMeritus** [LIBCAS/DL4DH#32]
@bodnarIQ @MLhotak prosim o zapojeni testovaci instance vuci NK
- potrebujeme v ramci vystupu religionisticke mapy vyznamu overi automatizovanou praci na datech - a kvalitu vystupu projektu

**Comment by JanMeritus** [comment]
@valekfrantisek melo by byt zapojeno, prosim o vyzkouseni

**Comment by valekfrantisek** [comment]
@JanMeritus @bodnarIQ 

### Nefunkční?
- Testováno na uuid:27366eb0-8a34-11e6-84e2-005056827e51 (Čech: Politický týdenník katolický, celý ročník 1930).
- vypadá to, že export je prázdný
- u TEI exportu je hláška úspěšná, ale žádný soubor se neobjeví (JSON se exportuje, i když v něm neneí obsah)
- i v NKP Kramenrius se to tváří, že neexistuje ALTO ani OCR, ale já už u sebe mám z NKP export OCR (a bylo i ALTO); např uuid:00d79160-8b54-11e6-ae94-005056825209 - kde se nám to tedy ztratilo? Je to kvůli tomu, že je to pouze DNNT?

#### Další test
- další test na uuid:165c8470-6f69-11e6-a429-001018b5eb5c (Čech: Politický týdenník katolický, celý ročník 1904). Je volně dostupný, v NKP Kramerius je OCR, ale nejdou mi celkově zobratit metadata (chybí "<>" v pravo nahoře).
- Export celého ročníku FAILED (byť hláška je úspěšná)
- číslo 1 (uuid:df303c90-7133-11e6-90a5-005056825209) údajně SUCCESSFUL, ale žádného exportu jsem se nedočkal, JSON, TEI, různá nastavení, nic... žádný nový soubor se neobjevuje...

- navíc je https://dl4dh.inqool.cz/export nějaký zakousaný (po "úspěšném exportu" se po aktualizaci okna nějakou chvíli v "Obohacené publikace" ani v "Vygenerované exporty" nic nezobrazuje)

**Comment by bodnarIQ** [comment]
Dobrý deň,

404 to hadze, pretoze sa pouziva ina url. Pri prvotnej implementacii som nevedel o existencii API pre ziskanie instancii Kramerii (spomenute v issue LIBCAS/DL4DH-Kramerius-plus#45 ) a url som do zdrojakov pre par najpouzivanejsich instancii nastavoval manualne, u NK som pouzil url `https://kramerius5.nkp.cz/search/api/v5.0`, ktore sa vyuziva pri ziskavani dat na https://www.digitalniknihovna.cz/nkp. 

Upravim K+, aby pouzival zoznam instancii z poskytnuteho rozhrania.

**Comment by JanMeritus** [comment]
@bodnarIQ jak to bezi? za mne napojeno, dalsi chyby v samostatnych issues
