### ISSUE TITLE
Metodika

### ISSUE THREAD

**Issue by daliboris** [LIBCAS/DL4DH#34]
# Metodika DL4DH

Návrh osnovy metodiky. (Body dodané 9. 2. jsou zobrazeny **tučně**.)

### RIV

[Definice druhů výsledků ve formátu .docx](https://www.isvavai.cz/dokumenty/definice_druhu_vysledku.docx)

> Výsledek „Metodika“ je souhrnem doporučených praktik a postupů schválených, certifikovaných nebo akreditovaných kompetenčně příslušným orgánem veřejné správy … a s jednoznačně vymezenými uživateli tak, aby tito uživatelé měli jistotu, že při jejím dodržení budou získané výsledky průkazné, opakovatelné a že se jich lze dovolat.
>
> Výsledek „Metodika“ realizoval původní výsledky výzkumu a vývoje, které byly uskutečněny autorem nebo týmem, jehož byl autor členem.
>
> … musí být takové schválení/certifikace/akreditace uděleno na základě vypracování dvou nezávislých oponentních posudků …
### Příklady metodik

Metodiky od roku 2016, oblast humanitních věd, poskytovatel MK, vyhledáno v [RIVu](https://www.isvavai.cz/riv)

- [Metodika logické ochrany digitálních dat](http://invenio.nusl.cz/record/371612?ln=cs)
- [Metodika uchování a prezentace multimediálních dat](http://invenio.nusl.cz/record/432001?ln=cs)
- [Metodika evidence dokladů hmotné kultury v narativních pramenech se zaměřením na zpřístupnění kulturně historických informací v cizojazyčných pramenech](https://www.isvavai.cz/riv?s=rozsirene-vyhledavani&ss=detail&n=0&h=RIV%2F67985963%3A_____%2F21%3A00540930%21RIV21-MK0-67985963)
- [Certifikovaná metodika s názvem Století informace: svět informatiky a elektrotechniky – počítačový svět v nás](https://www.isvavai.cz/riv?s=jednoduche-vyhledavani&ss=detail&n=0&h=RIV%2F68407700%3A21230%2F19%3A00336397%21RIV20-MK0-21230___), [NÚŠL](http://invenio.nusl.cz/record/408923)
- [Certifikovaná metodika digitalizace všech typů obrazových zdrojů filmových materiálů](http://invenio.nusl.cz/record/369582/files/nusl-369582_1.pdf)
- [Interpretace fotografie z hlediska obsažených obrazových informací. Metodika maximalizace reálného využití informací poskytovaných historickým fotografickým materiálem jako solitérní památkou a v kontextu používaných databázových systémů evidence pro prohloubení určení a poznání zobrazeného v každodenní praxi při identifikaci osob, míst, ateliérů apod.](https://www.npu.cz/publikace/Interpretace%20fotografie%20z%20hlediska%20obsazenych%20obrazovych%20informaci.pdf)

## Úvahy o metodice DL4DH

Ideální čtenář/uživatel metodiky

- \(A) provozovatel digitální knihovny Kramerius
- \(B) badatel v oblasti digitálních humanitních věd
  - \(B1) programátor
  - \(B2) „neprogramátor“

Co by se čtenáři/uživatelé měli dozvědět

- \(A) provozovatel digitální knihovny Kramerius
  - co je součástí dat v Krameriu
    - **jenom základ, detaily formou odkazu na dokumentaci**
  - co je součástí dat v Krameriu+
    - **víc než základ, detaily ale formou odkazu na dokumentaci**
  - Kramerius+
    - nasazení (požadavky na HW a SW),
    - konfigurace (interní a externí služby)
    - provoz (aktualizace SW, synchronizace dat)
- \(B) badatel v oblasti digitálních humanitních věd
  - jaká data jsou k dispozici (v Krameriu)
    - **obsah (pokud možno vyčíslené v procentech; čísla za KNAV, MZK, NK)**
      - **z jakého období jsou publikace** 
      -  **z jaké produkce publikace pocházejí**
      - **jaké jazyky díla obsahují**
      - **jaká jsou témata (beletrie, noviny, odborné)**
    - objem digitalizátů
    - struktura (monografie, periodika, virtuální sbírky…)
    - ne/dostupnost dat chráněných autorským zákonem
  - jaké údaje o datech jsou k dispozici **(v Krameriu, Krameriu+, NDK balíčcích)**
    - metadata (k dokumentu, k obrázkům)
    - obrazová data
    - textová data
  - v jakém formátu jsou údaje o datech k dispozici
    - CSV/TSV
    - JSON
    - TEI
    - ALTO
  - schémata poskytovaných dat
    - XSD, RNG pro ALTO a TEI
    - JSON Schema **(bude k definované?)**
  - jak jsou údaje o datech zachyceny v jednotlivých formátech
    - **(jakým způsobem zpracovat? komparačně jako tabulku, každý formát samostatně?)**
  - práce s Krameriem (přepnutí na Kramerius+)
  - jak pracovat s DL4DH Feederem správně, aby uživatel dospěl ke správným výsledkům 
    - **(výsledkům čeho? vyhledávání, nebo bádání?)**
  - práce s uživatelských rozhraním Krameria+/DL4DH Feederu
  - API pro práci s Krameriem+ a DL4DH Feederem
  - příklady výzkumných témat
    - podrobná studie i s výsledky
    - náměty na další studie s předpokládaným scénářem prací

 Další užitečné informace

- **cíle projektu**
- **předpokládaní uživatelé**
- **digitalizace v knihovnách**
  - **historie**
  - **aktuální stav**
  - **instituce využívající Krameria**
- nové metody v humanitních vědách
  - DH
  - velké objemy dat
- formáty poskytovaných dat
  - syntaktická pravidla jednotlivých formátů
  - výhody a nevýhody formátů
  - standardizační autority (ALTO, TEI)
- právní rámec
  - autorský zákon
  - směrnice EU (data pro výzkum)
- obohacování textových dat
  - jaké nástroje jsou k dispozici
  - které nástroje se dostaly do DL4DH a proč
- architektura zvoleného řešení
  - technologie
  - komponenty systému
    - komunikace mezi nimi
  - zdůvodnění zvolených řešení
- slabá místa DL4DH
  - k čemu se nedá použít
- informace o jiných podobných projektech

**Comment by bezovam** [comment]
Pardon, nikdy jsem metodiku nepsala, tak možná moje komentáře půjdou trochu mimo
Kramerius+ nasazení - počítá se i s přesným popisem (bod po bodu) toho, jak se má nástroj nainstalovat nebo se bude jednat jen o popis HW a SW, které je nutné mít, aby bylo možné ho používat?

**Comment by daliboris** [comment]
Není potřeba se omlouvat, metodika se dělá pro všechny, kdo mají o danou problematiku zájem, pokud možno i pro nováčky. Děkuju za otázku, která mě samotného nenapadla. Takže se pokusím za sebe odpovědět.

Cílem metodiky je, aby její čtenáři/uživatelé mohli postupovat bod po dobu (pokud možno) a dospěli ke stejnému výsledku, tj. např. k fungujícímu Krameriu+.

Na druhou stranu, by metodika mohla být nadčasová, aby se nemusela často měnit. Takže by to mohlo vypadat tak, že v ní bude odkaz na stránky DL4DH, kde by měl být proces instalace a nasazení Krameria+ podrobně popsán. Pokud se bude Kramerius+ opravovat nebo dále vyvíjet, informace o nasazení na jeho stránkách by měly být neustále aktuální, takže metodiku nebude nutné přepisovat.

Přikláním se k posledně zmíněnému řešení, tj. v metodice popsat obecně požadavky na HW a SW, popř. obecné kroky při nasazení + na detaily odkázat na stránky DL4DH. Musíme si pohlídat, aby na stránkách DL4DH informace o nasazení byla k dispozici, a to už v době odevzdávání metodiky.

**Comment by motyc** [comment]
Borisi, jak jsem již psal do emailu, nepřijde mi šťastné vést diskusi k metodice zde na GitHub. Text nejde přímo komentovat či navrhovat změny, není myslím vhodné míchat to s vývojem nástrojů a navíc si myslím, že psaní a související diskuse by měli probíhat neveřejně.

**Comment by daliboris** [comment]
Myslím, že aktuální podoba metodiky, které jsem teď dal podobu bodů, se ke komentování na GitHubu hodí. Navíc je to zatím ve velmi obecné rovině, žádné detaily.

Další formu a postup prací na metodice, které by vyhovovala všem, jsem chtěl probrat na čtvrteční schůzce.

Napadají mě zatím tyto možnosti:

- ponechat metodiku na veřejném GitHubu (pokud tam nebudou neveřejná data, interní informace, přístupové údaje ap.)
- mít neveřejný GitHub jenom pro metodiku (umožňují to už i pro bezplatné účty na GitHubu)

Formulace textu:

- navrhovat změny v GitHubu pomocí issue (ocitováním textu a návrhu opravy)
- řešit vše ve sdíleném dokumentu
- otevírat issue na GitHubu pro vybraná témata z metodiky, která vyžadují podrobnější diskusi (v komentářích na Dokmentu Google by to mohlo být nepřehledné)

Výsledný text:

- zpracovat text v Markdownu na GitHubu
- zpracovat text ve sdíleném dokumentu (Dokumenty Google)
  - později převést do jiného formátu, který bude lépe udržovatelný do budoucna
- využít jiný formalizovaný model (např. [ReSpec](https://github.com/OCFL/respec), viz [Oxford Common File Layout Specification](https://ocfl.io/draft/spec/))

**Comment by hlageek** [comment]
ad výsledný text: @daliboris cítím mezi řádky preferenci githubu, chápu to, taky by se mi dobře pracovalo ve vlastním editoru, ale myslím, že se k metodice potřebuje vyjadřovat širší skupina lidí, pro kterou by git workflow mohla být zbytečná bariéra. Takže spíš Google Docs. Nebo, to na kolaboraci používám já, kompromis v podobě HackMD.

Jinak bych se také přikláněl k tomu věci provozního charakteru během trvání projektu neřešit na githubu. Něco jiného je pak nějaký finální text, který může žít v repozitáři pro další verzování a věcnější diskuse, než jaké se pojí s přípravou draftu.

**Comment by motyc** [comment]
Ok, proberme to na nadcházející schůzce. Osobně pro podobnou práci preferuji Google Docs/Drive), kde je možné přímo reagovat atd. GitHub je na některé věci super, ale zrovna na kolektivní psaní a brainstorming mi přijde zbytečně komplikovaný a nepřehledný.

K věcnému hledisku - mám pocit, že návrh struktury se nově posunul více od metodiky směrem k manuálu. Hodně ale záleží, kam ty body začleníme a jak budou popsané. Určitě je podstatné, aby metodika obsahově přenositelná, tj. sice svázaná s nástroji DL4DH, ale aby v principu abstrahovala k obecnějším sdělením. Jedině tak bude uplatnitelná dlouhodoběji.

**Comment by daliboris** [comment]
> návrh struktury se nově posunul více od metodiky směrem k manuálu

Popis naší metodiky v přihlášce DL4DH (alespoň doufám, že jde o platnou formulaci z přihlášky; nemám ji k dispozici, vycházím z Jarmiliných podkladů):

“Metodika bude popisovat, jakým způsobem lze pomocí v projektu vyvíjených nástrojů těžit data z digitálních knihoven. Metodika představí různé možnosti exportu dat a na praktických příkladech uvede způsoby jejich konkrétního využití vědci. - Odborní uživatelé digitálních knihoven, vědečtí pracovníci v oblasti digitálních humanitních věd, vědecké týmy využívající funkcionalitu vyvíjených nástrojů (zástupci z řad archeologů, etnologů, religionistů, historiků).”

V čem vidíš, @motyc, rozdíl mezi metodikem a manuálem?

Existuje několik významů slova metodika (citováno z [Akademického slovníku cizích slov](https://prirucka.ujc.cas.cz/?slovo=metodika)).

**metodika** [-dy-], -y ž <r < ř>
1. _pracovní postup_: m. výzkumu
2. _nauka o metodě vyučování_: m. češtiny
3. _nauka o metodě vědecké práce_

Metodiku vzešlou v rámci DL4DH jsem chápal v prvním významu, čemuž podle mě odpovídá definice typu výsledku, tak popis výstupu v přihlášce.

**Comment by motyc** [comment]
@daliboris manuál chápu jako návod ke konkrétní aplikaci/nástroji (apod.); metodiku chápu jako popis obecnějších principů, kdy nějaký postup vede k určitému cíli, ale nástroje si pro daný účel můžu vybrat víceméně takové, jaké jsou aktuálně nejvhodnější k dispozici. Samozřejmě to trošku zjednodušuji, ale prostě od metodiky bych čekal primárně to, že mi umožní věc pochopit a reprodukovat postup, od manuálu čekám, že budu vědět, jaké tlačítko mám zmáčknout, aby to něco udělalo...

Ten posun myslím směrem od toho, co jsi posílal před týdnem a prezentoval na schůzi. Nicméně jak jsem psal výše. Hodně záleží, jakou formou a do jakoho kontextu se ty Tvé nadhozy zapracují. Rozhodně to nechci nějak zatracovat jako špatné!

**Comment by daliboris** [comment]
> aby metodika obsahově přenositelná, tj. sice svázaná s nástroji DL4DH, ale aby v principu abstrahovala k obecnějším sdělením. Jedině tak bude uplatnitelná dlouhodoběji

Neumím si teď moc představit ona _obecnější sdělení_. Pokud by byla typu "zvolili jsme třívrstvou architekturu kvůli lepšímu výkonu, dlouhodobým úlohám", "replikace databáze Apache Solr", "obohacení textových dat pomocí aktuálních nástrojů poskytovaných infrastrukturou LINDAT/CLARIAH-CZ", "morfologická anotace ve formátu Universal Dependencies, protože..." atp., určitě to tam má své místo, ale přijde mi to na jednu stranu triviální (třívrstvá architektura), závislé na aktuálním řešení Krameria (replikace Apache Solr) a obvyklé (použití nejnovějších trendů typu Univerzal Dependencies).

Proto si myslím, že zvolené řešení, tj. DL4DH, závisí na tom, co máme k dispozici (Krameria, UDPipe) a že pro jiné instituce to v tomhle směru bude použitelné jenom částečně a po nějakou dobu.

Z obecnějších, nadčasovějších věcí mě napadá spíš něco ve stylu _best practice_ v DH, ale nerad bych, aby z metodiky vznikla učebnice DH pro práci s velkými daty, a to z několika důvodů:

- návody pro DH existují jinde
- různé výzkumy vyžadují různá data (jejich obohacení ap.), nejsme schopni vše v DL4DH pokrýt
- nemáme na to (časové, lidské) kapacity

**Comment by zabak** [comment]
Ano, metodika musí být zaměřena na to, jak využít konkrétní nástroje, které dáváme k dispozici.  Zobecnění bude spíš na úrovni toho, co všechno ty nástroje umožňuji, k čemu se dají využít.

**Comment by motyc** [comment]
@daliboris Zkusím to konkretizovat - třeba toto mi typicky přijde jako údaje, které nepatří do metodiky, ale do manuálu k dané aplikaci:

> - Kramerius+
> -- nasazení (požadavky na HW a SW),
> -- konfigurace (interní a externí služby)
> -- provoz (aktualizace SW, synchronizace dat)

Bude to ale lepší probrat zítra.

**Comment by daliboris** [comment]
Jestli to tedy chápeme stejně:

Formulace typu `Pro vyhledání většího počtu relevantních dokumentů můžete použít hledání podle lemmatu, nejen konkrétního tvaru slova.` je na úrovni metodiky, věta `Pro vyhledání lemmatu (všech tvarů slova) v dokumentech zaškrtněte volbu 'všechny tvary'.` je na úrovni manuálu.

Podle mě by v naší metodice mohlo a mělo být obojí. Samozřejmě tam, kde to bude funkční, a jen do/od určité míry obecnosti i konkrétnosti.

**Comment by motyc** [comment]
Ano, potvrzuji, chápeme se stejně.
