### ISSUE TITLE
Obohatenie textu o narodní autority

### ISSUE THREAD

**Issue by bodnarIQ** [LIBCAS/DL4DH#5]
Obohatenie prebehne pomocou služby [NameTag](http://lindat.mff.cuni.cz/services/nametag/run.php). Služba nameTag nám vráti text otagovaný o rozpoznané entity. Z nich sa vyextrahujú entity otagované ako `PX` - Personal Names. Do DB sa uložia metadáta potrebné pre vytvorenie TEI formátu - Názov entity, pozícia zažiatku, pozícia konca, typ entity, ... Tieto dáta nebudú indexované - nebude možné v nich vyhľadávať, bolo by to zbytočné - vyhľadávanie by nemalo žiadnu pridanú hodnotu, rovnako by sa našli publikácie pri vyhľadávaní v plainTexte/lemmatizovanom texte. Bude možné vyexportovať všetky rozoznané menné entity z daného dokumentu - táto funkcionalita bude použitá hlavne pre zaslanie potrebných informácii do TEI Convertoru pre vytvorenie a uloženie TEI formátu.

Problém nastáva pri prelinkovaní mennej autority s externou databázou. Nemáme efektívny spôsob, akým by sme mohli určiť konkrétnu autoritu, na ktorú autor publikácie myslel pri písaní. Toto by sme mohli vyriešiť tak, že pri rozoznaní mennej entity by sa vytvoril iba URL link do databáze autorít, ale nie na stránku konkrétnej autority, ale na stránku ktorá sa zobrazí pri vyhľadávaní daného reťazca. Vyzeralo by to nejak takto:

_[Karel IV.](https://www.wikidata.org/w/index.php?search=Karel+IV.&title=Special:Search&profile=advanced&fulltext=1&advancedSearch-current=%7B%7D&ns0=1&ns120=1) byl syn dědičky [Přemyslovců Elišky](https://www.wikidata.org/w/index.php?search=Eli%C5%A1ka+P%C5%99emyslovna&title=Special:Search&profile=advanced&fulltext=1&advancedSearch-current=%7B%7D&ns0=1&ns120=1) a českého krále [Jana Lucemburského](https://www.wikidata.org/w/index.php?search=Jan+Lucembursk%C3%BD&title=Special:Search&profile=advanced&fulltext=1&advancedSearch-current=%7B%7D&ns0=1&ns120=1)._

Jediný spôsob, akým by sme mohli odkazovať na presné záznamy v menných autoritách je manuálna správa rozpoznaných entít a ich prelinku ku konkrétnej mennej autorite knihovníkmi/administrátormi, no pri takomto množsvte dát mi to príde veľmi neefektívne. 

Bolo by toto dostatočné riešenie čo sa týka prelinkovania menných autorít do externej databázy?

EDIT: Budeme potrebovať odkazovať na viaceré externé DB? Na čom to bude závisieť? Budeme to mať dopredu definované? Môžme sa spoliehať na to, že pre jeden "typ" metadat(napr. metadata o rozpoznanych mennych autoritach) budeme odkazovať stále na rovnakú externú DB?

**Comment by bodnarIQ** [comment]
Hlavný problém je Entity Linking - https://github.com/LIBCAS/DL4DH/issues/11

**Comment by bukovskyIQ** [comment]
Bližší diskuze je v issue #11, tento issue může být zavřen.
