### ISSUE TITLE
Licenčné podmienky

### ISSUE THREAD

**Issue by bodnarIQ** [LIBCAS/DL4DH#6]
Kde nájdeme licenčné podmienky k danej publikácií, aké môžu byť, ako na základe nich budeme musieť obmedzovať prístup k publikácií?

Súčasťou FOXML je datastream _POLICY_ , ktorý vyzerý napríklad takto:

```
<foxml:datastream ID="POLICY" STATE="A" CONTROL_GROUP="E" VERSIONABLE="false">
    <foxml:datastreamVersion ID="POLICY.0" LABEL="" CREATED="2020-10-30T16:00:30.008Z" MIMETYPE="application/rdf+xml">
      <foxml:contentLocation TYPE="URL" REF="http://local.fedora.server/fedora/get/policy:public/POLICYDEF"/>
    </foxml:datastreamVersion>
</foxml:datastream>
```

K obsahu odkazu v <foxml:contentLocation> sa nedostanem, predpokladám že je k nemu prístup iba interne, vieme z toho ale nejakým spôsobom vyčítať typ licencie?

**Comment by inqool-bukovsky** [comment]
Bude řešeno až v průběhu. DNNT & zákon brát v potaz.
